config/routes.rb
Rails.application.routes.draw do

  resources :closements
  resources :histories
  resources :user_groups
  resources :customers, only: [:index,:destroy]
  resources :accounts, only: [:index,:destroy]
  devise_for :users, only: [:sessions]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   #account
  scope :controller => "accounts", :path => "/accounts" do

    get 'accounts', :to => "accounts#edit", as: "invoices"
    post 'accounts', :to =>"accounts#edit" , as: "acinvoices"
  end
  scope :controller => "accounts", :path => "/close" do

    get 'accounts', :to => "accounts#close_edit", as: "invoicesclo"
    post 'accounts', :to =>"accounts#close_edit" , as: "acinvoicesclo"
  end
  scope :controller => "accounts", :path => "/closeall" do

    get 'accounts', :to => "accounts#close_all", as: "invoicescloa"
    post 'accounts', :to =>"accounts#close_all" , as: "acinvoicescloa"
  end
  scope :controller => "accounts", :path => "/open" do

    get 'accounts', :to => "accounts#open_edit", as: "invoicesope"
    post 'accounts', :to =>"accounts#open_edit" , as: "acinvoicesope"
  end
  scope :controller => "accounts", :path => "/new" do

    get 'accounts', :to => "accounts#new", as: "ninvoices"
    post 'accounts', :to =>"accounts#new" , as: "nacinvoices"
  end
  scope :controller => "accounts", :path => "/create" do

    get 'accounts', :to => "accounts#create", as: "cinvoices"
    post 'accounts', :to =>"accounts#create" , as: "cacinvoices"
  end

  scope :controller => "accounts", :path => "/query" do

    get 'accounts', :to => "accounts#query" ,as: "qinvoices"
    post 'accounts', :to =>"accounts#query" ,as: "qacinvoices"
  end
  scope :controller => "accounts", :path => "/printe" do

    get 'accounts', :to => "accounts#printe" ,as: "einvoices"
    post 'accounts', :to =>"accounts#printe" ,as: "eacinvoices"
  end
  scope :controller => "accounts", :path => "/printp" do

    get 'accounts', :to => "accounts#printp" ,as: "pinvoices"
    post 'accounts', :to =>"accounts#printp" ,as: "pacinvoices"

  end
  scope :controller => "accounts", :path => "/resultp" do

    get 'accounts', :to => "accounts#resultp" ,as: "rpinvoices"
    post 'accounts', :to =>"accounts#resultp" ,as: "rpacinvoices"
  end
  scope :controller => "accounts", :path => "/resulte" do

    get 'accounts', :to => "accounts#resulte" ,as: "reinvoices"
    post 'accounts', :to =>"accounts#resulte" ,as: "reacinvoices"
  end
  scope :controller => "accounts", :path => "/resultp1" do

    get 'accounts', :to => "accounts#resultp1" ,as: "rp1invoices"
    post 'accounts', :to =>"accounts#resultp1" ,as: "rp1cinvoices"
  end
  scope :controller => "accounts", :path => "/printp1" do

    get 'accounts', :to => "accounts#printp1" ,as: "p1invoices"
    post 'accounts', :to =>"accounts#printp1" ,as: "p1cinvoices"
  end
  #customer
  scope :controller => "customers", :path => "/customers" do

    get 'customers', :to => "customers#edit",as:"mantaincust"
    post 'customers', :to =>"customers#edit",as:"mpantaincust"
  end

  scope :controller => "customers", :path => "/new" do

    get 'customers', :to => "customers#new",as:"nmantaincust"
    post 'customers', :to =>"customers#new",as:"npantaincust"
  end
  scope :controller => "customers", :path => "/create" do

    get 'customers', :to => "customers#create",as:"cnmantaincust"
    post 'customers', :to =>"customers#create",as:"cnpantaincust"
  end
  scope :controller => "customers", :path => "/query" do

    get 'customers', :to => "customers#query",as:"qnmantaincust"
    post 'customers', :to =>"customers#query",as:"qnpantaincust"
  end
  scope :controller => "histories", :path => "/query" do

    get 'histories', :to => "histories#query",as:"gquery_history"
    post 'histories', :to =>"histories#query",as:"pquery_history"
  end
  scope :controller => "user_groups", :path => "/query" do

    get 'user_groups', :to => "user_groups#query",as:"gquery_user_groups"
    post 'user_groups', :to =>"user_groups#query",as:"pquery_user_groups"
  end
  scope :controller => "closements", :path => "/query" do

    get 'closements', :to => "closements#query",as:"gclosements_groups"
    post 'closements', :to =>"closements#query",as:"pclosements_groups"
  end

  # scope :controller => "accounts", :path => "/download" do
  #   post 'accounts', :to =>"accounts#download_pdf",as: "dpacinvoices"
  # end


  scope "(:locale)", locale: /zh_TW|en/ do
    root "menubars#show_menu"
    resources :menubars, param: :menu_id do
      collection do
        get :show_menu
        post :reset, :search
      end
      member do
        get :form
      end
    end
  end

  # bar_meeting GET   /foo/meetings/:id(.:format) events#show
  # bar_meetings POST /foo/meetings(.:format)     events#create
end

app/models/closement.rb
class Closement < ApplicationRecord
end

app/controllers/closements_controller.rb
class ClosementsController < ApplicationController
  before_action :user_group
  before_action :set_closement, only: [:show, :edit, :update, :destroy]

  # GET /closements
  # GET /closements.json
  def index
    @menubars = Menubar.all
    @menubar = @menubars.first
    @menus = Menubar.order(:menu_sn)
    @closements = Closement.all
  end

  # GET /closements/1
  # GET /closements/1.json
  def query
    @closements = Closement.all
    if params[:close_day].present?
      @closements.update_all(close_day: params[:close_day].to_i)
    end
  end

  def user_group
    staff = UserGroup.select("won_staff","group").where(login: authenticate_user![:login])  #authenticate_user![:login]
    staff.each do |variable|
      @wonstaff =variable.won_staff
      @group =variable.group
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_closement
      @closement = Closement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def closement_params
      params.require(:closement).permit(:close_day)
    end
end

app/helpers/closements_helper.rb
module ClosementsHelper
end

app/views/closements/_changeform.html.erb
<% if @group!="3" then %>
<%= render "common/menu1" %>
<% else %>
  <%= render "common/menu" %>
<% end %>
<h1>結帳日維護</h1>
　
<table class="table">

  <thead >

    <tr>
      <td>項次</td>
      <td>結帳日</td>
   　　  <td>&nbsp;&nbsp;處理</td>

    </tr>
  </thead>
　　　　
  <tbody id="bodyrow">
　
    <% @closements.each_with_index do |closement,index| %>
      <tr >
        <td><input class="box border-0 form-control" type="text" size="2" onfocus="this.blur()" value=<%= index+1 %>></td>
        <td><input class="box border-2 form-control" maxlength="2" size="2"   type="text"  id="close_day_input"  value=<%=closement.close_day %>><input id ="old_close_day" hidden="hidden" value=<%=closement.close_day %>> </input></td>
        <td >
            <button  id="closement_yes" class="btn btn-primary" remote="true" >確定</button>
        </td>
      </tr>

    <% end %>

  </tbody>
　　
</table>

app/views/closements/_form.html.erb
<%= simple_form_for(@closement) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :close_day %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/closements/edit.html.erb
<h1>Editing Closement</h1>

<%= render 'form', closement: @closement %>

<%= link_to 'Show', @closement %> |
<%= link_to 'Back', closements_path %>

app/views/closements/index.html.erb
<% if @group!="3"%>
<div class="row menu">
<%= render "common/menu" %>
</div>
  <% end %>

  <% if @group == "3"%>
    <%= render "changeform" %>
  <% end %>

app/views/closements/new.html.erb
<h1>New Closement</h1>

<%= render 'form', closement: @closement %>

<%= link_to 'Back', closements_path %>

app/views/closements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Close day:</strong>
  <%= @closement.close_day %>
</p>

<%= link_to 'Edit', edit_closement_path(@closement) %> |
<%= link_to 'Back', closements_path %>