config/routes.rb
Rails.application.routes.draw do

  resources :closements
  resources :histories
  resources :user_groups
  resources :customers, only: [:index,:destroy]
  resources :accounts, only: [:index,:destroy]
  devise_for :users, only: [:sessions]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   #account
  scope :controller => "accounts", :path => "/accounts" do

    get 'accounts', :to => "accounts#edit", as: "invoices"
    post 'accounts', :to =>"accounts#edit" , as: "acinvoices"
  end
  scope :controller => "accounts", :path => "/close" do

    get 'accounts', :to => "accounts#close_edit", as: "invoicesclo"
    post 'accounts', :to =>"accounts#close_edit" , as: "acinvoicesclo"
  end
  scope :controller => "accounts", :path => "/closeall" do

    get 'accounts', :to => "accounts#close_all", as: "invoicescloa"
    post 'accounts', :to =>"accounts#close_all" , as: "acinvoicescloa"
  end
  scope :controller => "accounts", :path => "/open" do

    get 'accounts', :to => "accounts#open_edit", as: "invoicesope"
    post 'accounts', :to =>"accounts#open_edit" , as: "acinvoicesope"
  end
  scope :controller => "accounts", :path => "/new" do

    get 'accounts', :to => "accounts#new", as: "ninvoices"
    post 'accounts', :to =>"accounts#new" , as: "nacinvoices"
  end
  scope :controller => "accounts", :path => "/create" do

    get 'accounts', :to => "accounts#create", as: "cinvoices"
    post 'accounts', :to =>"accounts#create" , as: "cacinvoices"
  end

  scope :controller => "accounts", :path => "/query" do

    get 'accounts', :to => "accounts#query" ,as: "qinvoices"
    post 'accounts', :to =>"accounts#query" ,as: "qacinvoices"
  end
  scope :controller => "accounts", :path => "/printe" do

    get 'accounts', :to => "accounts#printe" ,as: "einvoices"
    post 'accounts', :to =>"accounts#printe" ,as: "eacinvoices"
  end
  scope :controller => "accounts", :path => "/printp" do

    get 'accounts', :to => "accounts#printp" ,as: "pinvoices"
    post 'accounts', :to =>"accounts#printp" ,as: "pacinvoices"

  end
  scope :controller => "accounts", :path => "/resultp" do

    get 'accounts', :to => "accounts#resultp" ,as: "rpinvoices"
    post 'accounts', :to =>"accounts#resultp" ,as: "rpacinvoices"
  end
  scope :controller => "accounts", :path => "/resulte" do

    get 'accounts', :to => "accounts#resulte" ,as: "reinvoices"
    post 'accounts', :to =>"accounts#resulte" ,as: "reacinvoices"
  end
  scope :controller => "accounts", :path => "/resultp1" do

    get 'accounts', :to => "accounts#resultp1" ,as: "rp1invoices"
    post 'accounts', :to =>"accounts#resultp1" ,as: "rp1cinvoices"
  end
  scope :controller => "accounts", :path => "/printp1" do

    get 'accounts', :to => "accounts#printp1" ,as: "p1invoices"
    post 'accounts', :to =>"accounts#printp1" ,as: "p1cinvoices"
  end
  #customer
  scope :controller => "customers", :path => "/customers" do

    get 'customers', :to => "customers#edit",as:"mantaincust"
    post 'customers', :to =>"customers#edit",as:"mpantaincust"
  end

  scope :controller => "customers", :path => "/new" do

    get 'customers', :to => "customers#new",as:"nmantaincust"
    post 'customers', :to =>"customers#new",as:"npantaincust"
  end
  scope :controller => "customers", :path => "/create" do

    get 'customers', :to => "customers#create",as:"cnmantaincust"
    post 'customers', :to =>"customers#create",as:"cnpantaincust"
  end
  scope :controller => "customers", :path => "/query" do

    get 'customers', :to => "customers#query",as:"qnmantaincust"
    post 'customers', :to =>"customers#query",as:"qnpantaincust"
  end
  scope :controller => "histories", :path => "/query" do

    get 'histories', :to => "histories#query",as:"gquery_history"
    post 'histories', :to =>"histories#query",as:"pquery_history"
  end
  scope :controller => "user_groups", :path => "/query" do

    get 'user_groups', :to => "user_groups#query",as:"gquery_user_groups"
    post 'user_groups', :to =>"user_groups#query",as:"pquery_user_groups"
  end
  scope :controller => "closements", :path => "/query" do

    get 'closements', :to => "closements#query",as:"gclosements_groups"
    post 'closements', :to =>"closements#query",as:"pclosements_groups"
  end

  # scope :controller => "accounts", :path => "/download" do
  #   post 'accounts', :to =>"accounts#download_pdf",as: "dpacinvoices"
  # end


  scope "(:locale)", locale: /zh_TW|en/ do
    root "menubars#show_menu"
    resources :menubars, param: :menu_id do
      collection do
        get :show_menu
        post :reset, :search
      end
      member do
        get :form
      end
    end
  end

  # bar_meeting GET   /foo/meetings/:id(.:format) events#show
  # bar_meetings POST /foo/meetings(.:format)     events#create
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
    belongs_to :customer,optional: true
    belongs_to :account,optional: true
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :user_group
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @menubars = Menubar.all
    @menubar = @menubars.first
    @menus = Menubar.order(:menu_sn)
    @user_groups = UserGroup.all.where("[group] <> ?","3").page(params[:page]).per(10)


  end

  # GET /user_groups/1/edit
  def query

    @user_groups =  UserGroup.find_by(login: params[:login])
    @user_groups.update(group: params[:group])
    @user_groups=UserGroup.all

  end
  def user_group
    staff = UserGroup.select("won_staff","group").where(login: authenticate_user![:login])  #authenticate_user![:login]
    staff.each do |variable|
      @wonstaff =variable.won_staff
      @group =variable.group
    end
  end
  # POST /user_groups
  # POST /user_groups.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_group_params
      params.fetch(:user_group, {})
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_changeform.html.erb
<% if @group!="3" then %>
<%= render "common/menu1" %>
<% else %>
  <%= render "common/menu" %>
<% end %>

<h1>列印權限維護</h1>

<table class="table">

  <thead >

    <tr>
      <td>項次</td>
      <td>&nbsp;&nbsp;帳號</td>
      <td>&nbsp;業務人員 </td>
      <td>可全印</td>
 　　

    </tr>
  </thead>
    <%= paginate @user_groups, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
  <tbody id="bodyrow">
　
    <% @user_groups.each_with_index do |usergroup,index| %>
      <tr id=<%= index+1 %>>
        <td ><%= index+1 %></td>
        <td style="display:none;"><input id ="input<%=index+1%>"></td>
        <td><input class="box border-0 form-control" size="12"  type="text" onfocus="this.blur()"  id="uglogin"  value=<%=usergroup.login %>> </td>
        <td><input class="box border-0 form-control" size="14" type="text" onfocus="this.blur()" id="ugstaf" value=<%=usergroup.won_staff %>> </td>

        <td>
        &nbsp;&nbsp;  &nbsp;&nbsp;<input class="form-check-input" type="checkbox" id="uggroup"  <% if usergroup.group == "4" then %>checked> <%end%>





         </td>

      </tr>

    <% end %>

  </tbody>

</table>

app/views/user_groups/_form.html.erb
<%= simple_form_for(@user_group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing User Group</h1>

<%= render 'form', user_group: @user_group %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<div class="ugchange">
<%= render "changeform" %>
</div>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

<%= render 'form', user_group: @user_group %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>