config/routes.rb
Rails.application.routes.draw do

  resources :closements
  resources :histories
  resources :user_groups
  resources :customers, only: [:index,:destroy]
  resources :accounts, only: [:index,:destroy]
  devise_for :users, only: [:sessions]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   #account
  scope :controller => "accounts", :path => "/accounts" do

    get 'accounts', :to => "accounts#edit", as: "invoices"
    post 'accounts', :to =>"accounts#edit" , as: "acinvoices"
  end
  scope :controller => "accounts", :path => "/close" do

    get 'accounts', :to => "accounts#close_edit", as: "invoicesclo"
    post 'accounts', :to =>"accounts#close_edit" , as: "acinvoicesclo"
  end
  scope :controller => "accounts", :path => "/closeall" do

    get 'accounts', :to => "accounts#close_all", as: "invoicescloa"
    post 'accounts', :to =>"accounts#close_all" , as: "acinvoicescloa"
  end
  scope :controller => "accounts", :path => "/open" do

    get 'accounts', :to => "accounts#open_edit", as: "invoicesope"
    post 'accounts', :to =>"accounts#open_edit" , as: "acinvoicesope"
  end
  scope :controller => "accounts", :path => "/new" do

    get 'accounts', :to => "accounts#new", as: "ninvoices"
    post 'accounts', :to =>"accounts#new" , as: "nacinvoices"
  end
  scope :controller => "accounts", :path => "/create" do

    get 'accounts', :to => "accounts#create", as: "cinvoices"
    post 'accounts', :to =>"accounts#create" , as: "cacinvoices"
  end

  scope :controller => "accounts", :path => "/query" do

    get 'accounts', :to => "accounts#query" ,as: "qinvoices"
    post 'accounts', :to =>"accounts#query" ,as: "qacinvoices"
  end
  scope :controller => "accounts", :path => "/printe" do

    get 'accounts', :to => "accounts#printe" ,as: "einvoices"
    post 'accounts', :to =>"accounts#printe" ,as: "eacinvoices"
  end
  scope :controller => "accounts", :path => "/printp" do

    get 'accounts', :to => "accounts#printp" ,as: "pinvoices"
    post 'accounts', :to =>"accounts#printp" ,as: "pacinvoices"

  end
  scope :controller => "accounts", :path => "/resultp" do

    get 'accounts', :to => "accounts#resultp" ,as: "rpinvoices"
    post 'accounts', :to =>"accounts#resultp" ,as: "rpacinvoices"
  end
  scope :controller => "accounts", :path => "/resulte" do

    get 'accounts', :to => "accounts#resulte" ,as: "reinvoices"
    post 'accounts', :to =>"accounts#resulte" ,as: "reacinvoices"
  end
  scope :controller => "accounts", :path => "/resultp1" do

    get 'accounts', :to => "accounts#resultp1" ,as: "rp1invoices"
    post 'accounts', :to =>"accounts#resultp1" ,as: "rp1cinvoices"
  end
  scope :controller => "accounts", :path => "/printp1" do

    get 'accounts', :to => "accounts#printp1" ,as: "p1invoices"
    post 'accounts', :to =>"accounts#printp1" ,as: "p1cinvoices"
  end
  #customer
  scope :controller => "customers", :path => "/customers" do

    get 'customers', :to => "customers#edit",as:"mantaincust"
    post 'customers', :to =>"customers#edit",as:"mpantaincust"
  end

  scope :controller => "customers", :path => "/new" do

    get 'customers', :to => "customers#new",as:"nmantaincust"
    post 'customers', :to =>"customers#new",as:"npantaincust"
  end
  scope :controller => "customers", :path => "/create" do

    get 'customers', :to => "customers#create",as:"cnmantaincust"
    post 'customers', :to =>"customers#create",as:"cnpantaincust"
  end
  scope :controller => "customers", :path => "/query" do

    get 'customers', :to => "customers#query",as:"qnmantaincust"
    post 'customers', :to =>"customers#query",as:"qnpantaincust"
  end
  scope :controller => "histories", :path => "/query" do

    get 'histories', :to => "histories#query",as:"gquery_history"
    post 'histories', :to =>"histories#query",as:"pquery_history"
  end
  scope :controller => "user_groups", :path => "/query" do

    get 'user_groups', :to => "user_groups#query",as:"gquery_user_groups"
    post 'user_groups', :to =>"user_groups#query",as:"pquery_user_groups"
  end
  scope :controller => "closements", :path => "/query" do

    get 'closements', :to => "closements#query",as:"gclosements_groups"
    post 'closements', :to =>"closements#query",as:"pclosements_groups"
  end

  # scope :controller => "accounts", :path => "/download" do
  #   post 'accounts', :to =>"accounts#download_pdf",as: "dpacinvoices"
  # end


  scope "(:locale)", locale: /zh_TW|en/ do
    root "menubars#show_menu"
    resources :menubars, param: :menu_id do
      collection do
        get :show_menu
        post :reset, :search
      end
      member do
        get :form
      end
    end
  end

  # bar_meeting GET   /foo/meetings/:id(.:format) events#show
  # bar_meetings POST /foo/meetings(.:format)     events#create
end

app/views/common/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog"
           aria-labelledby="myModalLabel"
           aria-hidden="true"
           data-backdrop="static"
           data-keyboard="true">
  <div class="modal-dialog  modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h3 class="modal-title"></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" id="close" class="close btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/common/_fontsize.erb
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
   <i class="fa fa-text-height fa-2x" ></i>
&nbsp <select id="changfontsize" class="custom-select" width="80" style="width: 80px" required>
   <option value="26px" <%= "selected" if @fontsize=="16px" %> >26px</option>
   <option value="22px" <%= "selected" if @fontsize=="16px" %> >22px</option>
   <option value="16px" <%= "selected" if @fontsize=="16px" %> selected>16px</option>
   <option value="14px" <%= "selected" if @fontsize=="14px" %> >14px</option>
   <option value="12px" <%= "selected" if @fontsize=="12px" %> >12px</option>
   <option value="10px" <%= "selected" if @fontsize=="10px" %> >10px</option>
</select>

app/views/common/_menu.html.erb
<h3>月報表管理系統</h3>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <!-- Links -->
  <ul class="navbar-nav">
    <!-- Dropdown -->

    <% last_parent_menu_id = '' %>
    <% last_menu_id = '' %>
    <% @menus.each do |menubar| %>
        <% if last_menu_id.present? && menubar.menu_id[0,6] != last_menu_id[0,6] %>
          </div>
        </li>
        <% end %>
      <% if menubar.parent_menu_id.present? && menubar.parent_menu_id == menubar.menu_id[0,6] %>
        <% if menubar.program_url.present? %>
          <a class="dropdown-item" href=<%= menubar.program_url %>><%= menubar.menu_name.strip %></a>
        <% else %>
          <a class="dropdown-item" href="#"><%= menubar.menu_name.strip %></a>
        <% end %>
      <% else %>
      <% if menubar.parent_menu_id.blank? && menubar.menu_id.present? %>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
            <%= menubar.menu_name.strip %>
          </a>
          <div class="dropdown-menu">
      <% end %>
      <% end %>
      <% last_parent_menu_id = menubar.parent_menu_id %>
      <% last_menu_id = menubar.menu_id  %>
    <% end %>
          </div>
        </li>
  </ul>

  <ul class="navbar-nav">
    <%= link_to "登出", destroy_user_session_path, method: :delete, :class => "btn btn-info btn-sm" %>
  </ul>
</nav>

app/views/common/_menu1.html.erb
<h3>月報表管理系統</h3>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <!-- Links -->
  <ul class="navbar-nav">
    <!-- Dropdown -->
          <a class="nav-link" href="/accounts" >
            帳單異動
          </a>
          <a class="nav-link" href="/customers">
            客戶資料維護
          </a>
  </ul>

  <ul class="navbar-nav">
    <%= link_to "登出", destroy_user_session_path, method: :delete, :class => "btn btn-info btn-sm" %>
  </ul>
</nav>

app/views/common/_single_form.html.erb
<!-- 進入作業系統，顯示選單、作業系統 GridView及 Form 內容資料  -->
<div class="container-fluid">
  <div class="row menu">
  <%= render "common/menu" %>
  </div>
  <div class="row toolbar">
  <%= render "common/toolbar" %>
  </div>
  <div class="row">
    <div class="sidenav col-sm-3 col-md-3 col-lg-3">
      <%= render "gridview" %>
    </div>
    <div class="myform col-sm-9 col-md-9 col-lg-9">
      <%= render "form" %>
    </div>
    <div class="myerror col-sm-9 col-md-9 col-lg-9">
    </div>
  </div>
</div>

<%= render 'common/dialog' %>

app/views/common/_toolbar.html.erb
<% if @form_state=='browse' || @form_state.blank? then %>
<button type="button" class="new_button btn btn-primary btn-sm"><%= (I18n.t :new, scope: [ :buttons ]) %></button>
<button type="button" class="edit_button btn btn-primary btn-sm"><%= (I18n.t :edit, scope: [ :buttons ]) %></button>
<button type="button" class="delete_button btn btn-primary btn-sm"><%= (I18n.t :delete, scope: [ :buttons ]) %></button>
<button type="button" class="query_button btn btn-warning btn-sm"><%= (I18n.t :query, scope: [ :buttons ]) %></button>
<button type="button" class="print_button btn btn-info btn-sm"><%= (I18n.t :print, scope: [ :buttons ]) %></button>
<button type="button" class="barcode_button btn btn-dark btn-sm"><%= (I18n.t :barcode, scope: [ :buttons ]) %></button>
<% else %>
<button type="button" class="submit_button btn btn-success btn-sm" onclick='TestFun();'><%= (I18n.t :submit, scope: [ :buttons ]) %></button>
<%= button_to (I18n.t :reset, scope: [ :buttons ]), reset_menubars_path(), remote: true, class: "reset_button btn btn-danger btn-sm" %>
<% end %>