config/routes.rb
Rails.application.routes.draw do

  resources :closements
  resources :histories
  resources :user_groups
  resources :customers, only: [:index,:destroy]
  resources :accounts, only: [:index,:destroy]
  devise_for :users, only: [:sessions]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   #account
  scope :controller => "accounts", :path => "/accounts" do

    get 'accounts', :to => "accounts#edit", as: "invoices"
    post 'accounts', :to =>"accounts#edit" , as: "acinvoices"
  end
  scope :controller => "accounts", :path => "/close" do

    get 'accounts', :to => "accounts#close_edit", as: "invoicesclo"
    post 'accounts', :to =>"accounts#close_edit" , as: "acinvoicesclo"
  end
  scope :controller => "accounts", :path => "/closeall" do

    get 'accounts', :to => "accounts#close_all", as: "invoicescloa"
    post 'accounts', :to =>"accounts#close_all" , as: "acinvoicescloa"
  end
  scope :controller => "accounts", :path => "/open" do

    get 'accounts', :to => "accounts#open_edit", as: "invoicesope"
    post 'accounts', :to =>"accounts#open_edit" , as: "acinvoicesope"
  end
  scope :controller => "accounts", :path => "/new" do

    get 'accounts', :to => "accounts#new", as: "ninvoices"
    post 'accounts', :to =>"accounts#new" , as: "nacinvoices"
  end
  scope :controller => "accounts", :path => "/create" do

    get 'accounts', :to => "accounts#create", as: "cinvoices"
    post 'accounts', :to =>"accounts#create" , as: "cacinvoices"
  end

  scope :controller => "accounts", :path => "/query" do

    get 'accounts', :to => "accounts#query" ,as: "qinvoices"
    post 'accounts', :to =>"accounts#query" ,as: "qacinvoices"
  end
  scope :controller => "accounts", :path => "/printe" do

    get 'accounts', :to => "accounts#printe" ,as: "einvoices"
    post 'accounts', :to =>"accounts#printe" ,as: "eacinvoices"
  end
  scope :controller => "accounts", :path => "/printp" do

    get 'accounts', :to => "accounts#printp" ,as: "pinvoices"
    post 'accounts', :to =>"accounts#printp" ,as: "pacinvoices"

  end
  scope :controller => "accounts", :path => "/resultp" do

    get 'accounts', :to => "accounts#resultp" ,as: "rpinvoices"
    post 'accounts', :to =>"accounts#resultp" ,as: "rpacinvoices"
  end
  scope :controller => "accounts", :path => "/resulte" do

    get 'accounts', :to => "accounts#resulte" ,as: "reinvoices"
    post 'accounts', :to =>"accounts#resulte" ,as: "reacinvoices"
  end
  scope :controller => "accounts", :path => "/resultp1" do

    get 'accounts', :to => "accounts#resultp1" ,as: "rp1invoices"
    post 'accounts', :to =>"accounts#resultp1" ,as: "rp1cinvoices"
  end
  scope :controller => "accounts", :path => "/printp1" do

    get 'accounts', :to => "accounts#printp1" ,as: "p1invoices"
    post 'accounts', :to =>"accounts#printp1" ,as: "p1cinvoices"
  end
  #customer
  scope :controller => "customers", :path => "/customers" do

    get 'customers', :to => "customers#edit",as:"mantaincust"
    post 'customers', :to =>"customers#edit",as:"mpantaincust"
  end

  scope :controller => "customers", :path => "/new" do

    get 'customers', :to => "customers#new",as:"nmantaincust"
    post 'customers', :to =>"customers#new",as:"npantaincust"
  end
  scope :controller => "customers", :path => "/create" do

    get 'customers', :to => "customers#create",as:"cnmantaincust"
    post 'customers', :to =>"customers#create",as:"cnpantaincust"
  end
  scope :controller => "customers", :path => "/query" do

    get 'customers', :to => "customers#query",as:"qnmantaincust"
    post 'customers', :to =>"customers#query",as:"qnpantaincust"
  end
  scope :controller => "histories", :path => "/query" do

    get 'histories', :to => "histories#query",as:"gquery_history"
    post 'histories', :to =>"histories#query",as:"pquery_history"
  end
  scope :controller => "user_groups", :path => "/query" do

    get 'user_groups', :to => "user_groups#query",as:"gquery_user_groups"
    post 'user_groups', :to =>"user_groups#query",as:"pquery_user_groups"
  end
  scope :controller => "closements", :path => "/query" do

    get 'closements', :to => "closements#query",as:"gclosements_groups"
    post 'closements', :to =>"closements#query",as:"pclosements_groups"
  end

  # scope :controller => "accounts", :path => "/download" do
  #   post 'accounts', :to =>"accounts#download_pdf",as: "dpacinvoices"
  # end


  scope "(:locale)", locale: /zh_TW|en/ do
    root "menubars#show_menu"
    resources :menubars, param: :menu_id do
      collection do
        get :show_menu
        post :reset, :search
      end
      member do
        get :form
      end
    end
  end

  # bar_meeting GET   /foo/meetings/:id(.:format) events#show
  # bar_meetings POST /foo/meetings(.:format)     events#create
end

app/models/account.rb
class Account < ApplicationRecord
attr_accessor :acc_staff
attr_accessor :paymark
attr_accessor :mail_show_mark
attr_accessor :mail_until_closeday
attr_accessor :mail_show_mark_clsday
has_one :user_group
  #has_many :customer
belongs_to :customer, foreign_key: "cust_id"

end

app/helpers/accounts_helper.rb
module AccountsHelper

  #EXCEL含小計
  def printe_xlsx(yyyy_mm,acc_yyyy_mm,user_name)

  if @group=="1" then
  custid = Customer.select(:cust_id).where(won_staff: user_name)
  if File.exist?("#{Rails.root}/public/#{yyyy_mm+"倉儲費用"}.xlsx")
    File.delete("#{Rails.root}/public/#{yyyy_mm+"倉儲費用"}.xlsx")
  end
  workbook = WriteXLSX.new("#{Rails.root}/public/#{yyyy_mm+"倉儲費用"}.xlsx")


  # Add a worksheet1
  worksheet1 = workbook.add_worksheet(yyyy_mm+'倉儲費用')
  # worksheet1.margins = 0.2
  worksheet1.margin_left = 0.5
  worksheet1.margin_right = 0.5
  worksheet1.margin_top = 0.5
  worksheet1.margin_bottom = 0.5


  worksheet1.repeat_rows(0, 3)


  worksheet1.set_footer('&CPage &P of &N');

  # The activate() method is used to specify which worksheet1 is initially visible in a multi-sheet workbook:
  worksheet1.activate



  format_title = workbook.add_format(:num_format => '@', :size => 16, :bold => 1)
  format_subtitle = workbook.add_format(:num_format => '@', :size => 14, :bold => 0)
  format_string_center = workbook.add_format(:num_format => '@', :align => 'center')
  format_string_center_background = workbook.add_format(:num_format => '@', :align => 'center', :bg_color => 'silver')
  format_string = workbook.add_format(:num_format => '@')
  format_string_background = workbook.add_format(:num_format => '@', :bg_color => 'silver')


  format_string_shrink = workbook.add_format()
  format_string_shrink.set_num_format('@')
  format_string_shrink.set_shrink(1)

  format_number = workbook.add_format(:num_format => '#,##0')

  worksheet1.set_column('A:A', 5)    # 項次
  worksheet1.set_column('B:B', 8)    # 客戶編號
  worksheet1.set_column('C:C', 18)   # 客戶名稱
  worksheet1.set_column('D:D', 8)    # 帳單編號
  worksheet1.set_column('E:E', 12)   # 帳單金額
  worksheet1.set_column('F:F', 13)   # 帳單名稱
  worksheet1.set_column('G:G', 15)   # 其他說明


  item = 0
  item_count = 0
  worksheet1.set_row(0, 25)
  worksheet1.write(item, 2, "海灣文件倉儲管理系統", format_title)

  item = 1
  worksheet1.set_row(1, 20)
  worksheet1.write(item, 2, yyyy_mm+"倉儲費用", format_subtitle)
  worksheet1.write(item, 5, "列印日期："+Date.today.strftime("%Y/%m/%d"), format_string)

  item = 2
  worksheet1.write(item, 5, "列印人員："+user_name)

  item = 3
  worksheet1.write(item, 0, "項次", format_string_center_background)
  worksheet1.write(item, 1, "客戶編號", format_string_background)
  worksheet1.write(item, 2, "客戶名稱", format_string_background)
  worksheet1.write(item, 3, "帳單編號", format_string_background)
  worksheet1.write(item, 4, "帳單金額", format_string_background)
  worksheet1.write(item, 5, "客戶類別名稱", format_string_background)
  worksheet1.write(item, 6, "其他說明", format_string_background)

  worksheet1.freeze_panes(item+1, 0)    # Freeze the item row

  worksheet1.autofilter( 'A4:G4' )


  acc_total = 0

  Account.joins(:customer).select("accounts.cust_id, cust_name, cust_type, acc_kind, acc_no, acc_cost, acc_note")
                          .where(accounts: {acc_date: acc_yyyy_mm,cust_id: custid})
                          .where.not(accounts: {acc_cost: 0})
                          .order("cust_id ASC, cust_type ASC").each { |row|

    item = item + 1
    item_count =  item_count + 1
    worksheet1.write(item, 0, item_count, format_string_center)
    worksheet1.write(item, 1, "#{row['cust_id']}", format_string)
    worksheet1.write(item, 2, "#{row['cust_name']}", format_string_shrink)
    worksheet1.write(item, 3, "#{row['acc_kind']}-#{row['acc_no']}", format_string)
    worksheet1.write(item, 4, "#{row['acc_cost']}", format_number)
    worksheet1.write(item, 5, "#{row['cust_type']}", format_string_shrink)
    worksheet1.write(item, 6, "#{row['acc_note']}", format_string_shrink)
    acc_total = acc_total + row['acc_cost'] if !row['acc_cost'].nil?

  }


  worksheet1.write(2, 2, "總金額："+acc_total.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse, format_string)

  worksheet2 = workbook.add_worksheet(yyyy_mm+'倉儲費用小計')

  worksheet1.margin_left = 0.5
  worksheet1.margin_right = 0.5
  worksheet1.margin_top = 0.5
  worksheet1.margin_bottom = 0.5

  worksheet2.repeat_rows(0, 3)

  worksheet2.set_footer('&CPage &P of &N');

  worksheet2.activate

  format_title = workbook.add_format(:num_format => '@', :size => 16, :bold => 1)
  format_subtitle = workbook.add_format(:num_format => '@', :size => 14, :bold => 0)
  format_string_center = workbook.add_format(:num_format => '@', :align => 'center')
  format_string_center_background = workbook.add_format(:num_format => '@', :align => 'center', :bg_color => 'silver')
  format_string = workbook.add_format(:num_format => '@')
  format_string_background = workbook.add_format(:num_format => '@', :bg_color => 'silver')

  format_string_shrink = workbook.add_format()
  format_string_shrink.set_num_format('@')
  format_string_shrink.set_shrink(1)


  format_number = workbook.add_format(:num_format => '#,##0')

  worksheet2.set_column('A:A', 5)    # 項次
  worksheet2.set_column('B:B', 8)    # 客戶編號
  worksheet2.set_column('C:C', 40)   # 客戶名稱
  worksheet2.set_column('D:D', 15)    # 帳單金額

  item_count = 0
  worksheet2.set_row(0, 25)
  worksheet2.write(item, 2, "海灣文件倉儲管理系統", format_title)

  item = 1
  worksheet2.set_row(1, 20)
  worksheet2.write(item, 2, yyyy_mm+"倉儲費用", format_subtitle)
  worksheet2.write(item, 3, "列印日期："+Date.today.strftime("%Y/%m/%d"), format_string)

  item = 2
  worksheet2.write(item, 3, "列印人員："+user_name)

  item = 3
  worksheet2.write(item, 0, "項次", format_string_center_background)
  worksheet2.write(item, 1, "客戶編號", format_string_background)
  worksheet2.write(item, 2, "客戶名稱", format_string_background)
  worksheet2.write(item, 3, "小計金額", format_string_background)

  worksheet2.freeze_panes(item+1, 0)    # Freeze the item row

  worksheet2.autofilter( 'A4:D4' )

  #
  acc_total = 0

  Account.joins(:customer).select("accounts.cust_id, cust_name, sum(acc_cost) as acc_cost")
                          .group("accounts.cust_id, cust_name")
                          .where(accounts: {acc_date: acc_yyyy_mm,cust_id: custid})
                          .where.not(accounts: {acc_cost: 0})
                          .order("cust_id ASC").each { |row|

    item = item + 1
    item_count =  item_count + 1
    worksheet2.write(item, 0, item_count, format_string_center)
    worksheet2.write(item, 1, "#{row['cust_id']}", format_string)
    worksheet2.write(item, 2, "#{row['cust_name']}", format_string_shrink)
    worksheet2.write(item, 3, "#{row['acc_cost']}", format_number)
    acc_total = acc_total + row['acc_cost'] if !row['acc_cost'].nil?

  }


  worksheet2.write(2, 2, "總計金額："+acc_total.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse, format_string)

  worksheet1.activate

  workbook.close

elsif @group.to_i >= 3 #有權限印全部的人

   custid = Customer.select(:cust_id).where(won_staff: user_name) #使用業務人員名稱找客戶
   #資訊部權限及印總報表業務
  if custid.size == 0 || @group == "4" then
  if File.exist?("#{Rails.root}/public/#{yyyy_mm+"倉儲費用"}.xlsx")
    File.delete("#{Rails.root}/public/#{yyyy_mm+"倉儲費用"}.xlsx")
  end
   workbook = WriteXLSX.new("#{Rails.root}/public/#{yyyy_mm+"倉儲費用"}.xlsx")


   # Add a worksheet1
   worksheet1 = workbook.add_worksheet(yyyy_mm+'倉儲費用')
   # worksheet1.margins = 0.2
   worksheet1.margin_left = 0.5
   worksheet1.margin_right = 0.5
   worksheet1.margin_top = 0.5
   worksheet1.margin_bottom = 0.5


   worksheet1.repeat_rows(0, 3)


   worksheet1.set_footer('&CPage &P of &N');

   # The activate() method is used to specify which worksheet1 is initially visible in a multi-sheet workbook:
   worksheet1.activate



   format_title = workbook.add_format(:num_format => '@', :size => 16, :bold => 1)
   format_subtitle = workbook.add_format(:num_format => '@', :size => 14, :bold => 0)
   format_string_center = workbook.add_format(:num_format => '@', :align => 'center')
   format_string_center_background = workbook.add_format(:num_format => '@', :align => 'center', :bg_color => 'silver')
   format_string = workbook.add_format(:num_format => '@')
   format_string_background = workbook.add_format(:num_format => '@', :bg_color => 'silver')


   format_string_shrink = workbook.add_format()
   format_string_shrink.set_num_format('@')
   format_string_shrink.set_shrink(1)

   format_number = workbook.add_format(:num_format => '#,##0')

   worksheet1.set_column('A:A', 5)    # 項次
   worksheet1.set_column('B:B', 8)    # 客戶編號
   worksheet1.set_column('C:C', 18)   # 客戶名稱
   worksheet1.set_column('D:D', 8)    # 帳單編號
   worksheet1.set_column('E:E', 12)   # 帳單金額
   worksheet1.set_column('F:F', 13)   # 帳單名稱
   worksheet1.set_column('G:G', 15)   # 其他說明


   item = 0
   item_count = 0
   worksheet1.set_row(0, 25)
   worksheet1.write(item, 2, "海灣文件倉儲管理系統", format_title)

   item = 1
   worksheet1.set_row(1, 20)
   worksheet1.write(item, 2, yyyy_mm+"倉儲費用", format_subtitle)
   worksheet1.write(item, 5, "列印日期："+Date.today.strftime("%Y/%m/%d"), format_string)

   item = 2
   worksheet1.write(item, 5, "列印人員："+user_name)

   item = 3
   worksheet1.write(item, 0, "項次", format_string_center_background)
   worksheet1.write(item, 1, "客戶編號", format_string_background)
   worksheet1.write(item, 2, "客戶名稱", format_string_background)
   worksheet1.write(item, 3, "帳單編號", format_string_background)
   worksheet1.write(item, 4, "帳單金額", format_string_background)
   worksheet1.write(item, 5, "客戶類別名稱", format_string_background)
   worksheet1.write(item, 6, "其他說明", format_string_background)

   worksheet1.freeze_panes(item+1, 0)    # Freeze the item row

   worksheet1.autofilter( 'A4:G4' )


   acc_total = 0

   Account.joins(:customer).select("accounts.cust_id, cust_name, cust_type, acc_kind, acc_no, acc_cost, acc_note")
                           .where(accounts: {acc_date: acc_yyyy_mm})
                           .where.not(accounts: {acc_cost: 0})
                           .order("cust_id ASC, cust_type ASC").each { |row|

     item = item + 1
     item_count =  item_count + 1
     worksheet1.write(item, 0, item_count, format_string_center)

app/views/accounts/_new.html.erb
<p style="display:none;" id="notice"><%= notice %></p>
<p </p>
<p </p>


<table class="table table-hover">

  <thead >
    <style>
    input.normal {
      border: 2px solid red;
    }

    input.round1 {
      border: 3px solid grey;
      border-radius: 5px;
    }

    input.round2 {
      border: 4px solid red;
      border-radius: 111px;
    }

    input.round3 {
      border: 2px solid red;
      border-radius: 12px;
    }
    </style>

    <tr >

      <td>客戶編號</td>
      <td>客戶類別名稱</td>
      <td align="center" valign="center">類　別</td>
      <td align="center" valign="center">單　　號</td>
      <td align="center" valign="center">年份</td>
      <td align="center" valign="center">月份</td>
         <td style="display:none;"> </td>
      <td align="center" valign="center">費用</td>
      <td align="center" valign="center">備註</td>

        <td>處理      </td>
           <td> </td>
          <% if @group=="3" then%>
     <div id="wonstaff" value=<%=@wonstaff%>><%=@wonstaff%></div>
     <%end%>
    </tr>
  </thead>
  <tbody id="bodyrow">
　

      <tr >

        <td style="display:none;"><input name="account[id]" id ="input" ></td>
        <td> <input class="col box round1 form-control" maxlength="5" size="4"  type="text"  id="input0"  > </td>
        <td> <input class="col box round1 form-control" maxlength="15" size="16" type="text" id="input1" > </td>
        <td> <input class="col box border-0 form-control" size="2" type="text" id="input2"  value="WR"  > </td>
        <td> <input class="col box round1 form-control" maxlength="4"size="3"  type="text"  id="input3"  > </td>
        <td>
          <select id="date_yy" class="custom-select col-lg-15" required>
           <option value="2020">2020 </option>
           <option value="2021">2021 </option>
           <option value="2022">2022 </option>
           <option value="2023">2023 </option>
           <option value="2024">2024 </option>
           <option value="2025">2025 </option>
           <option value="2026">2026 </option>
           <option value="2027">2027 </option>
           <option value="2028">2028 </option>
           <option value="2029">2029 </option>
           <option value="2030">2030 </option>

         </select>     </td>
         <td>
           <select id="date_mm" class=" custom-select col-lg-15" required>
            <option value="01">01</option>
            <option value="02">02</option>
            <option value="03">03</option>
            <option value="04">04</option>
            <option value="05">05</option>
            <option value="06">06</option>
            <option value="07">07</option>
            <option value="08">08</option>
            <option value="09">09</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
          </select></td>



        <td style="display:none;"> <input class="box border-0 form-control" size="19"  type="text"　 id="input5"  > </td>
        <td> <input class="col box round1 form-control" maxlength="7" size="6"  type="text" style="text-align:right"  id="input6" ></td>
        <td> <input class="col box round1 form-control" size="20" type="text"   id="input7" ></td>
        <td style="display:none;">    </td>
        <td style="display:none;">    </td>
        <td id ='yesOrNoC'>
        <button id="acc_checkC" class="btn btn-primary" remote="true">確定</button>
         <button id="check_resetC" class="reset_button btn btn-danger"><%= (I18n.t :reset, scope: [ :buttons ]) %></button>
       　</td>
       <td>

      </td>

      </tr>



　　　　　　　
  </tbody>

</table>
   <% if @msgcreat!="" then %> <%=@msgcreat%> <% end %>

app/views/accounts/_resulte.html.erb
<%= link_to @dlfilenamee, reinvoices_path, :class => "barcode_button btn btn-dark btn-sm", :method => :get, data: {turbolinks: false} %>

app/views/accounts/_resultp1.html.erb
<%= link_to @dlfilenamep1, rp1invoices_path,:class => "barcode_button btn btn-dark btn-sm",  :method => :get, data: {turbolinks: false} %>

app/views/accounts/base64.js.erb
/**
*
*  Base64 encode / decode
*  http://www.webtoolkit.info/
*
**/

var Base64 = {

        // private property
       _keyStr : "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",

     // public method for encoding
     encode : function (input) {
               var output = "";
          var chr1, chr2, chr3, enc1, enc2, enc3, enc4;
             var i = 0;

         input = Base64._utf8_encode(input);

                while (i < input.length) {

                      chr1 = input.charCodeAt(i++);
                     chr2 = input.charCodeAt(i++);
                     chr3 = input.charCodeAt(i++);

                      enc1 = chr1 >> 2;
                   enc2 = ((chr1 & 3) << 4) | (chr2 >> 4);
                   enc3 = ((chr2 & 15) << 2) | (chr3 >> 6);
                  enc4 = chr3 & 63;

                      if (isNaN(chr2)) {
                                enc3 = enc4 = 64;
                 } else if (isNaN(chr3)) {
                         enc4 = 64;
                        }

                  output = output +
                 this._keyStr.charAt(enc1) + this._keyStr.charAt(enc2) +
                   this._keyStr.charAt(enc3) + this._keyStr.charAt(enc4);

             }

          return output;
    }

 // public method for decoding
     decode : function (input) {
               var output = "";
          var chr1, chr2, chr3;
             var enc1, enc2, enc3, enc4;
               var i = 0;

         input = input.replace(/[^A-Za-z0-9\+\/\=]/g, "");

          while (i < input.length) {

                      enc1 = this._keyStr.indexOf(input.charAt(i++));
                   enc2 = this._keyStr.indexOf(input.charAt(i++));
                   enc3 = this._keyStr.indexOf(input.charAt(i++));
                   enc4 = this._keyStr.indexOf(input.charAt(i++));

                    chr1 = (enc1 << 2) | (enc2 >> 4);
                     chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
                  chr3 = ((enc3 & 3) << 6) | enc4;

                 output = output + String.fromCharCode(chr1);

                       if (enc3 != 64) {
                         output = output + String.fromCharCode(chr2);
                      }
                 if (enc4 != 64) {
                         output = output + String.fromCharCode(chr3);
                      }

          }

          output = Base64._utf8_decode(output);

              return output;

     },

 // private method for UTF-8 encoding
      _utf8_encode : function (string) {
                string = string.replace(/\r\n/g,"\n");
            var utftext = "";

          for (var n = 0; n < string.length; n++) {

                       var c = string.charCodeAt(n);

                      if (c < 128) {
                         utftext += String.fromCharCode(c);
                        }
                 else if((c > 127) && (c < 2048)) {
                          utftext += String.fromCharCode((c >> 6) | 192);
                             utftext += String.fromCharCode((c & 63) | 128);
                       }
                 else {
                            utftext += String.fromCharCode((c >> 12) | 224);
                            utftext += String.fromCharCode(((c >> 6) & 63) | 128);
                          utftext += String.fromCharCode((c & 63) | 128);
                       }

          }

          return utftext;
   },

 // private method for UTF-8 decoding
      _utf8_decode : function (utftext) {
               var string = "";
          var i = 0;
                var c = c1 = c2 = 0;

               while ( i < utftext.length ) {

                  c = utftext.charCodeAt(i);

                 if (c < 128) {
                         string += String.fromCharCode(c);
                         i++;
                      }
                 else if((c > 191) && (c < 224)) {
                           c2 = utftext.charCodeAt(i+1);
                             string += String.fromCharCode(((c & 31) << 6) | (c2 & 63));
                         i += 2;
                   }
                 else {
                            c2 = utftext.charCodeAt(i+1);
                             c3 = utftext.charCodeAt(i+2);
                             string += String.fromCharCode(((c & 15) << 12) | ((c2 & 63) << 6) | (c3 & 63));
                           i += 3;
                   }

          }

          return string;
    }

app/views/accounts/colse_edit.html.erb
<%= render "showform" %>

app/views/accounts/create.html.erb
<div class="show">

</div>

app/views/accounts/new.html.erb
<div class="show">
<%= render "new" %>
</div>

app/views/accounts/query.html.erb
<div class="show">
<%= render "showform"  %>
</div>

app/views/accounts/resultp.html.erb
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">下載檔案名稱</th>
        </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
    <td><%= link_to @dlfilenamep, rpinvoices_path , :class => "barcode_button btn btn-dark btn-sm", :method => :get, data: {turbolinks: false} %>    </td>
        </tr>
    <tr>
      <th scope="row">2</th>
      <td> <%= render "resultp1" %>
</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td> <%= render "resulte" %>
</td>
        </tr>
    </tbody>
</table>